### ISSUE TITLE
increment() in achievement api not working

### ISSUE THREAD

**Issue by rama0x9** [defold/extension-gpgs#16]
.

**Comment by britzl** [comment]
Notice the official documentation for the increment() function:

https://developers.google.com/android/reference/com/google/android/gms/games/AchievementsClient#increment(java.lang.String,%20int)

"Increments an achievement by the given number of steps. The achievement must be an incremental achievement. Once an achievement reaches at least the maximum number of steps, it will be unlocked automatically. Any further increments will be ignored."

Perhaps the achievement was already unlocked?

Or, since this is an asynchronous operation there may be some delay between the call and the actual achievement steps being updated.

**Comment by subsoap** [comment]
@rama0x9 Can you give a sample of how you were using?

**Comment by rama0x9** [comment]
> @rama0x9 Can you give a sample of how you were using?
im using the example from this repo for testing all the features, nothing else. Like i said in the forums, everything but increment() works.

**Comment by britzl** [comment]
And how did you configure the achievement that you are trying to increment?

**Comment by rama0x9** [comment]
oh wow, fast reply ;) it's 6am in germany

i made several id's for different testings, each with different settings enabled/disabled
increment() should work where set() works or not?

**Comment by britzl** [comment]
We're in the same timezone and I woke early :-)

Can you please try to create a new achievement and try increment() on it? Increment won't work if it's already unlocked.

**Comment by rama0x9** [comment]
you sir can bet i tried it more than once :) 
in the end i always use set() to test if the achievement is working and it always does.
but i don't want to bother you any further with this as it seems its working for you and others, so it must be something on my end.
I can always keep track of the steps manually and use set() as a workaround.

**Comment by britzl** [comment]
You were right. I took a look at the code and it turns out that increment achievement called the wrong function. I was sure I had tested all functions properly but apparently I didn't. Thank you so much for your patience!

Released version 1.2.3 with a fix!
